YOUTUBE_API_KEY = "YOUR_API_YOUTUBE_KEY_HERE"

CHANNEL_HANDLE = "YOUTUBE_CHANNEL_HANDLE"
WEEKS_BACK = 12
LATEST_WEEKS = 12
MIN_FOCUS_WEEK_COMMENTS = 50

MAX_VIDEOS = 10       # Sicherheitslimit fürs MVP
MAX_COMMENTS = 1000   # Sicherheitslimit fürs MVP

# Claude
CLAUDE_API_KEY = "YOUR_API_KEY_HERE"
CLAUDE_MODEL = "claude-3-haiku-20240307"

BATCH_SIZE = 25
TEST_LIMIT = None